/*
 * EXT_INT_Config.h
 *
 *  Created on:
 *      Author:
 */

#ifndef MCAL_EXT_INT_EXT_INT_CONFIG_H_
#define MCAL_EXT_INT_EXT_INT_CONFIG_H_

/*
 *  SELECT SENSE_CONTROL0 OPTIONS:RISING_EDGE,FALLING_EDGE,ANY_LOGICAL_CHANGE,LOW_LEVEL
 */
#define    SENSE_CONTROL0      ANY_LOGICAL_CHANGE
/*
 *  SELECT SENSE_CONTROL1 OPTIONS:RISING_EDGE,FALLING_EDGE,ANY_LOGICAL_CHANGE,LOW_LEVEL
 */
#define    SENSE_CONTROL1      RISING_EDGE
/*
 *  SELECT SENSE_CONTROL2 OPTIONS:RISING_EDGE,FALLING_EDGE,ANY_LOGICAL_CHANGE,LOW_LEVEL
 */
#define    SENSE_CONTROL2      RISING_EDGE

#endif /* MCAL_EXT_INT_EXT_INT_CONFIG_H_ */
